name: Build

on:
  push:
    branches: [main, "**-dev"]
    paths: ["**/*.nim", "**/*.yml"]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash # necessary for windows

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME: nimpretty_t

    steps:
      - uses: actions/checkout@v3

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - name: Setup nim
        uses: iffy/install-nim@v4

      - name: Build
        run: nimble build -Y
